version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: "./"
      dockerfile: dockerfile 
    image: "putrasaut/golang-hello-world-with-docker-compose:2.0.0"
    ports:
      - 3000:3000
